"""new

Revision ID: 23e544db4a18
Revises: 
Create Date: 2022-11-18 15:42:27.030584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e544db4a18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), server_default='Vote', nullable=False),
    sa.Column('vote_limit', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ranked_choice', sa.Boolean(), nullable=False),
    sa.Column('type', sa.Enum('basic', 'fptp', 'approval', 'stv', 'ranked_pairs', name='votetype'), nullable=False),
    sa.Column('seats', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discord_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allowed_role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['vote.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote_choice',
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('choice_index', sa.Integer(), nullable=False),
    sa.Column('choice', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['vote_id'], ['vote.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vote_id', 'choice_index')
    )
    op.create_table('discord_vote_message',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('choices_start_index', sa.Integer(), nullable=False),
    sa.Column('numb_choices', sa.Integer(), server_default='20', nullable=False),
    sa.Column('part', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vote_id'], ['discord_vote.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vote_id'], ['vote.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('user_vote',
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('choice', sa.Integer(), nullable=False),
    sa.Column('preference', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['vote_id', 'choice'], ['vote_choice.vote_id', 'vote_choice.choice_index'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vote_id'], ['vote.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vote_id', 'user_id', 'choice')
    )
    op.create_table('discord_vote_choice',
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('choice_index', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('msg_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['msg_id'], ['discord_vote_message.message_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vote_id', 'choice_index'], ['vote_choice.vote_id', 'vote_choice.choice_index'], ),
    sa.PrimaryKeyConstraint('vote_id', 'choice_index')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discord_vote_choice')
    op.drop_table('user_vote')
    op.drop_table('discord_vote_message')
    op.drop_table('vote_choice')
    op.drop_table('discord_vote')
    op.drop_table('vote')
    # ### end Alembic commands ###
